version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.06
    steps:
      - run: sleep 5
  test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: <command>
workflows:
  build_and_test:
    jobs:
      - build
      - test
